agenda/contact/urls.py
from django.urls import path

from contact import views as contact_views

app_name = 'contact'

urlpatterns = [
    path('<int:contact_id>/', contact_views.contact,  # type: ignore
         name='contact'),
    path('search/', contact_views.search, name='search'),  # type: ignore
    path('', contact_views.index, name='index'),  # type: ignore
]

agenda/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agenda/contact/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# Create your models here.


class Category(models.Model):

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

agenda/contact/views/contact_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from contact.models import Contact

# Create your views here.


def index(request: HttpRequest) -> HttpResponse:
    contacts = Contact.objects.filter(show=True).order_by('-id')
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        'site_title': 'Contatos',
    }

    return render(request, 'contact/index.html', context=context)


def contact(request: HttpRequest, contact_id) -> HttpResponse:
    single_contact = get_object_or_404(Contact, id=contact_id, show=True)
    contact_name = f'{single_contact.first_name} {single_contact.last_name}'

    context = {
        'contact': single_contact,
        'site_title': contact_name
    }

    return render(request, 'contact/contact.html', context=context)


def search(request: HttpRequest) -> HttpResponse:
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        redirect('contact:index')

    contacts = Contact.objects.filter(show=True).filter(
        Q(first_name__icontains=search_value) |
        Q(last_name__icontains=search_value) |
        Q(phone__icontains=search_value) |
        Q(email__icontains=search_value)
    ).order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos',
        'search_value': search_value
    }

    return render(request, 'contact/index.html', context=context)

agenda/contact/templates/contact/contact.html
{% extends "global/base.html" %}

{% block content %}
<div class="single-contact">
    <h1 class="sigle-contact-name">
        {{ contact.first_name }} {{ contact.last_name }}
    </h1>
    <p><b>ID: </b>{{ contact.id }}</p>
    <p><b>E-mail: </b>{{ contact.email }}</p>
    <p><b>Phone: </b>{{ contact.phone }}</p>
    <p><b>Created Date: </b>{{ contact.created_date }}</p>
    <p><b>Description: </b>{{ contact.description }}</p>
    <p><b>Category: </b>{{ contact.category.name }}</p>
</div>
{% endblock content %}

agenda/contact/templates/contact/index.html
{% extends "global/base.html" %}

{% block content %}
    {% if page_obj %}
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contacts
                </caption>
                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">ID</th>
                        <th class="table-header">First Name</th>
                        <th class="table-header">Last Name</th>
                        <th class="table-header">Phone</th>
                        <th class="table-header">E-mail</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contact in page_obj %}
                        <tr class="table-row">
                            <td class="table-cel">
                                <a href="{% url "contact:contact" contact.id %}" class="table-link">
                                    {{ contact.id }}
                                </a>
                            </td>
                            <td class="table-cel">
                                {{ contact.first_name }}
                            </td>
                            <td class="table-cel">
                                {{ contact.last_name }}
                            </td>
                            <td class="table-cel">
                                {{ contact.phone }}
                            </td>
                            <td class="table-cel">
                                {{ contact.email }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <div class="single-contact">
                <h1 class="single-contact-name">Nenhum contato encontrado.</h1>
            </div>
    {% endif %}
{% endblock content %}